# Generated by Django 3.1.7 on 2021-03-17 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.user')),
                ('phone_number', models.CharField(max_length=20)),
                ('rollno', models.CharField(max_length=5)),
                ('stream', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='Faculty',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='designation',
            new_name='faculty_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_faculty',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_student',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
