# Generated by Django 3.1.7 on 2021-03-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210317_1124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Donor',
        ),
        migrations.RenameModel(
            old_name='Faculty',
            new_name='Ngo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_faculty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
    ]
