# Generated by Django 3.1.6 on 2021-02-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210225_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='text',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='uname',
            new_name='meal',
        ),
        migrations.AddField(
            model_name='tweet',
            name='address',
            field=models.TextField(default='', max_length=280),
        ),
        migrations.AddField(
            model_name='tweet',
            name='phone',
            field=models.CharField(default='', max_length=280),
        ),
    ]
